version: '3.9'

services:
  app:
    container_name: brawijaya-app
    build: .
    ports:
    - "8123:8123"
    restart: on-failure
    volumes:
    - api:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - brawijaya

  mysql:
    image: mysql:latest
    container_name: brawijaya-mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_PASSWORD"]
      interval: 60s
      retries: 15
      start_period: 30s
    volumes:
      - db:/var/lib/mysql
    networks:
      - brawijaya

volumes:
  api:
  db:

networks:
  brawijaya:
    driver: bridge